name: simple_count_down

version: 1.0.0

authors:
    - WiRight <ruslan.mahin1@gmail.com>

description: Simple CountDown timer

homepage: https://github.com/DizoftTeam/simple_count_down

environment:
    sdk: ">=2.6.0 <3.0.0"
    flutter: ">=1.10.0 <2.0.0"

dependencies:
    flutter:
        sdk: flutter
